Fix initramfs init script and add UEFI support in kernel

diff --git a/resources/initramfs_init b/resources/initramfs_init
--- a/resources/initramfs_init
+++ b/resources/initramfs_init
@@ -9,28 +9,51 @@ mount -t tmpfs     tmpfs     /tmp
 cd /tmp
 mkdir -p boot lower upper work system
 
-# Find the boot device
-IFS="
+# Find the boot device and switch_root
+find_system() {
+    IFS="
 "; for device in $(blkid); do
-    dev_path=$(echo $device | cut -d ":" -f 1)
+        dev_path=$(echo $device | cut -d ":" -f 1)
 
-    echo "Checking if $dev_path is the boot device"
+        echo "Checking if $dev_path is the boot device"
 
-    # Check if a device contains system.squashfs
-    # If so, mount system.squashfs and switch_root to it
-    if mount $dev_path boot && [ -e boot/system.squashfs ]; then
-        # Mount squashfs then mount an overlay fs over it so that the resulting directory is writable
-        if mount -t squashfs boot/system.squashfs lower && \
-           mount -t overlay \
-                 -o lowerdir=/tmp/lower,upperdir=/tmp/upper,workdir=/tmp/work \
-                 none system; then
-            echo "Found boot device $dev_path, switch_root now"
-            exec switch_root system /sbin/init
-        else
-            echo "Found boot device $dev_path, but failed to load system.squashfs"
+        # Check if a device contains system.squashfs
+        # If so, mount system.squashfs and switch_root to it
+        if ! mount $dev_path boot; then
+            echo "Failed to mount device $dev_path"
+            continue
+        fi
+
+        if ! [ -e boot/system.squashfs ]; then
+            echo "Failed to find system.squashfs on $dev_path"
+            umount boot
+            continue
+        fi
+
+        # Mount system.squashfs
+        if ! mount -t squashfs boot/system.squashfs lower; then
+            echo "Failed to mount system.squashfs on $dev_path"
             exec sh
         fi
-    fi
+
+        # Add an overlay fs on top of system.squashfs
+        if ! mount -t overlay \
+                -o lowerdir=/tmp/lower,upperdir=/tmp/upper,workdir=/tmp/work \
+                overlay system; then
+            echo "Failed to mount overlayfs for $dev_path"
+            exec sh
+        fi
+
+        echo "Found boot device $dev_path, switch_root now"
+        exec switch_root system /sbin/init
+    done
+
+    return 1
+}
+
+# Check multiple times since the device may not be set up yet
+for i in {1..5}; do
+    find_system || sleep 1
 done
 
 echo "Could not find the boot device"
